# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simulate_device_pb2 as simulate__device__pb2


class SimulateDeviceStub(object):
    """Interface exported by the server.
    A simple RPC.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimulateOppCL = channel.unary_unary(
                '/simulatedeivce.SimulateDevice/SimulateOppCL',
                request_serializer=simulate__device__pb2.Config.SerializeToString,
                response_deserializer=simulate__device__pb2.Status.FromString,
                )
        self.GetDeviceInfo = channel.unary_unary(
                '/simulatedeivce.SimulateDevice/GetDeviceInfo',
                request_serializer=simulate__device__pb2.Empty.SerializeToString,
                response_deserializer=simulate__device__pb2.DeviceInfo.FromString,
                )


class SimulateDeviceServicer(object):
    """Interface exported by the server.
    A simple RPC.

    """

    def SimulateOppCL(self, request, context):
        """Starts the OppCL simulation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulateDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimulateOppCL': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateOppCL,
                    request_deserializer=simulate__device__pb2.Config.FromString,
                    response_serializer=simulate__device__pb2.Status.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=simulate__device__pb2.Empty.FromString,
                    response_serializer=simulate__device__pb2.DeviceInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulatedeivce.SimulateDevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulateDevice(object):
    """Interface exported by the server.
    A simple RPC.

    """

    @staticmethod
    def SimulateOppCL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulatedeivce.SimulateDevice/SimulateOppCL',
            simulate__device__pb2.Config.SerializeToString,
            simulate__device__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulatedeivce.SimulateDevice/GetDeviceInfo',
            simulate__device__pb2.Empty.SerializeToString,
            simulate__device__pb2.DeviceInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
